# Site settings
title: Pandaの短期記憶
description: パンダの記憶は長くもたないので、記録する。
baseurl: ""
url: "https://tyanagity.github.io"

minimal_mistakes_skin: "default"  # または "air", "contrast", "dark" など

# Profile
author:
  name: "rPanda"
  avatar: "/assets/images/delivery_girl.gif" # 好きな画像のパスに変更
  bio: "Spirit Bear"
  location: "Tokyo, Japan"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/


# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
